### ISSUE TITLE
more bit？？？？

### ISSUE THREAD

**Issue by DanMerry** [facebookresearch/audioseal#46]
how to embed more bits into the audio?

**Comment by antoine-tran** [comment]
Hi, could you elaborate ? Did you mean the bits of the secret messages ?

You can modify the existing model card to have for example 32 instead of 16 bit-message in [here](https://github.com/facebookresearch/audioseal/blob/main/src/audioseal/cards/audioseal_wm_16bits.yaml#L10). For example:

```python

model = AudioSeal.load_generator("audioseal_wm_16bits", nbits=32)
...
```

Note that this might not always be optimal as the model is trained with different pertubed / augmented training data while embedding 16-bit messages. So other option is to train a new model (see our [ instruction notes](https://github.com/facebookresearch/audioseal/blob/main/docs/TRAINING.md)) , where you can specify the number of bits during the training. We provide an example recipe [here](https://github.com/facebookresearch/audiocraft/blob/main/audiocraft/grids/watermarking/kbits.py), where this [line](https://github.com/facebookresearch/audiocraft/blob/main/audiocraft/grids/watermarking/kbits.py#L62) is where the number of bits used for the training is specified

**Comment by antoine-tran** [comment]
@DanMerry I closed the issue. Feel free to re-open it if you still face the problem

**Comment by royrs** [comment]
@antoine-tran using the approach you wrote is not possible as the weights are for 16 bits and changing the number of bits should also change the MsgProcessor.

Is there a way using dora framework to fine-tune it to more bits? for example:
* Loading the weights of the 16 bit network and changing the msg processor + last layer to 32 bits
* Freezing all layers except those two and fine-tune only them

Or there isn't any "easy" way to do it with the training code given in the repo?

**Comment by rasaha-91** [comment]
@antoine-tran should "detector.output_dim": 32, also be changed when training with more bits? Asked in #101 since this issue is now closed.
